version: "3.3"
services:
  app:
    image: timokluser-dev/gbs_m120-dotnetdocker
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    hostname: app
    restart: "no"
  sdk:
    image: mcr.microsoft.com/dotnet/sdk:5.0.404
    command: [ "bash" ]
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    volumes:
      - .:/work
    hostname: sdk
    restart: "no"
